export const recipeCategories = [
  "Classic French Toast",
  "Vegetable Omelette",
  "Blueberry Pancakes",
  "Avocado Toast with Eggs",
  "Banana Walnut Muffins",
  "Grilled Chicken Caesar Salad",
  "Caprese Sandwich",
  "Quinoa Salad with Roasted Vegetables",
  "Turkey Club Wrap",
  "Vegetable Stir-Fry",
  "Spaghetti Bolognese",
  "Grilled Salmon with Lemon-Dill Sauce",
  "Stuffed Bell Peppers",
  "Chicken Tikka Masala",
  "Beef Tacos",
  "Bruschetta with Tomato and Basil",
  "Spinach Artichoke Dip",
  "Mini Quiches",
  "Stuffed Mushrooms",
  "Cucumber Rolls with Cream Cheese",
  "Greek Salad",
  "Cobb Salad",
  "Caesar Salad",
  "Watermelon Feta Salad",
  "Asian Slaw",
  "Roast Chicken with Garlic and Herbs",
  "Beef Wellington",
  "Lamb Curry",
  "Vegetable Lasagna",
  "Shrimp Scampi",
  "Garlic Mashed Potatoes",
  "Roasted Vegetables",
  "Buttered Corn",
  "Quinoa Pilaf",
  "Green Bean Almondine",
  "Chocolate Chip Cookies",
  "Apple Pie",
  "Banana Bread",
  "Blueberry Scones",
  "Carrot Cake",
];
